<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="UseCases\Billeteras\Commands\" />
    <Folder Include="UseCases\Billeteras\Handlers\" />
    <Folder Include="UseCases\Subastas\Commands\" />
    <Folder Include="UseCases\Subastas\Handlers\" />
  </ItemGroup>

</Project>
