// <auto-generated />
using System;
using Infraestructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SubastaDbContext))]
    [Migration("20260918001257_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Auditoria_Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Entidad_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Usuario_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Usuario_Id");

                    b.ToTable("Auditorias_Log");
                });

            modelBuilder.Entity("Domain.Billetera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Saldo_Disponible")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Saldo_Retenido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Saldo_Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Usuario_Id")
                        .HasColumnType("int");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Usuario_Id")
                        .IsUnique();

                    b.ToTable("Billeteras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Saldo_Disponible = 0m,
                            Saldo_Retenido = 0m,
                            Saldo_Total = 0m,
                            Usuario_Id = 1
                        },
                        new
                        {
                            Id = 2,
                            Saldo_Disponible = 105000m,
                            Saldo_Retenido = 45000m,
                            Saldo_Total = 150000m,
                            Usuario_Id = 2
                        },
                        new
                        {
                            Id = 3,
                            Saldo_Disponible = 200000m,
                            Saldo_Retenido = 0m,
                            Saldo_Total = 200000m,
                            Usuario_Id = 3
                        },
                        new
                        {
                            Id = 4,
                            Saldo_Disponible = 500m,
                            Saldo_Retenido = 0m,
                            Saldo_Total = 500m,
                            Usuario_Id = 4
                        });
                });

            modelBuilder.Entity("Domain.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Tecnologia"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Coleccionables"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Indumentaria"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Vehiculos"
                        });
                });

            modelBuilder.Entity("Domain.Puja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Comprador_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_Puja")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Subasta_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Comprador_Id");

                    b.HasIndex("Subasta_Id", "Monto");

                    b.ToTable("Pujas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comprador_Id = 3,
                            Fecha_Puja = new DateTime(2026, 9, 17, 20, 32, 57, 478, DateTimeKind.Local).AddTicks(9780),
                            Monto = 25000m,
                            Subasta_Id = 1
                        },
                        new
                        {
                            Id = 2,
                            Comprador_Id = 2,
                            Fecha_Puja = new DateTime(2026, 9, 17, 21, 2, 57, 478, DateTimeKind.Local).AddTicks(9780),
                            Monto = 45000m,
                            Subasta_Id = 1
                        },
                        new
                        {
                            Id = 3,
                            Comprador_Id = 3,
                            Fecha_Puja = new DateTime(2026, 9, 15, 21, 12, 57, 478, DateTimeKind.Local).AddTicks(9780),
                            Monto = 120000m,
                            Subasta_Id = 4
                        });
                });

            modelBuilder.Entity("Domain.Subasta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Categoria_Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Fecha_Fin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_Inicio")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Incremento_Minimo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Precio_Base")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url_Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Vendedor_Id")
                        .HasColumnType("int");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Categoria_Id");

                    b.HasIndex("Fecha_Fin")
                        .HasFilter("[Estado] = 'ACTIVA'");

                    b.HasIndex("Vendedor_Id");

                    b.HasIndex("Estado", "Categoria_Id", "Fecha_Fin");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Estado", "Categoria_Id", "Fecha_Fin"), new[] { "Titulo", "Precio_Base" });

                    b.ToTable("Subastas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria_Id = 1,
                            Descripcion = "Activa Estandar",
                            Estado = "ACTIVA",
                            Fecha_Fin = new DateTime(2026, 9, 17, 21, 37, 57, 478, DateTimeKind.Local).AddTicks(9780),
                            Fecha_Inicio = new DateTime(2026, 9, 17, 20, 12, 57, 478, DateTimeKind.Local).AddTicks(9780),
                            Incremento_Minimo = 500m,
                            Precio_Base = 10000m,
                            Titulo = "MacBook Pro",
                            Url_Imagen = "https://imgs.search.brave.com/J6-wF1GTePlaf-q8ScW9AG59Iiwp5IWXjXc42fJ1rqg/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93d3cu/YXBwbGUuY29tL3Yv/bWFjYm9vay1wcm8v/YXgvaW1hZ2VzL292/ZXJ2aWV3L3dlbGNv/bWUvaGVyb19lbmRm/cmFtZV9fZndldjll/Ymg0Mm1xX3hsYXJn/ZS5qcGc",
                            Vendedor_Id = 1
                        },
                        new
                        {
                            Id = 2,
                            Categoria_Id = 2,
                            Descripcion = "Activa Crítica",
                            Estado = "ACTIVA",
                            Fecha_Fin = new DateTime(2026, 9, 17, 21, 13, 57, 478, DateTimeKind.Local).AddTicks(9780),
                            Fecha_Inicio = new DateTime(2026, 9, 17, 19, 12, 57, 478, DateTimeKind.Local).AddTicks(9780),
                            Incremento_Minimo = 100m,
                            Precio_Base = 5000m,
                            Titulo = "Reloj Antiguo",
                            Url_Imagen = "https://imgs.search.brave.com/wLx1K_lbAiBugpCVvNHXj4bv3w48P3iTTWjqGKbuNNg/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9pLmVi/YXlpbWcuY29tL2lt/YWdlcy9nL3U0d0FB/T1N3YW5SWGcxYlEv/cy1sNDAwLndlYnA",
                            Vendedor_Id = 1
                        },
                        new
                        {
                            Id = 3,
                            Categoria_Id = 3,
                            Descripcion = "Próxima",
                            Estado = "PROGRAMADA",
                            Fecha_Fin = new DateTime(2026, 9, 19, 21, 12, 57, 478, DateTimeKind.Local).AddTicks(9780),
                            Fecha_Inicio = new DateTime(2026, 9, 18, 21, 12, 57, 478, DateTimeKind.Local).AddTicks(9780),
                            Incremento_Minimo = 1000m,
                            Precio_Base = 20000m,
                            Titulo = "Campera Cuero",
                            Url_Imagen = "https://imgs.search.brave.com/78zXlb1RFASO9v8TmGTyEHbjuQV3Z4Pb2jr9Y1A6mlA/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9odHRw/Mi5tbHN0YXRpYy5j/b20vRF9OUV9OUF82/NDA3NTEtTUxBNTEz/NDY3MjgyMTZfMDgy/MDIyLVcud2VicA",
                            Vendedor_Id = 1
                        },
                        new
                        {
                            Id = 4,
                            Categoria_Id = 4,
                            Descripcion = "Vencida con ganador",
                            Estado = "FINALIZADA",
                            Fecha_Fin = new DateTime(2026, 9, 16, 21, 12, 57, 478, DateTimeKind.Local).AddTicks(9780),
                            Fecha_Inicio = new DateTime(2026, 9, 12, 21, 12, 57, 478, DateTimeKind.Local).AddTicks(9780),
                            Incremento_Minimo = 5000m,
                            Precio_Base = 100000m,
                            Titulo = "Moto Honda",
                            Url_Imagen = "https://imgs.search.brave.com/OwjFjSvv0S8ohAmt395Fx2GCJChEk7U13LAuRYJt_lU/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9zY2Fs/ZXRodW1iLmxlcGFy/a2luZy5mci91bnNh/ZmUvMzAweDIyNS9o/dHRwczovL2Nsb3Vk/LmxlcGFya2luZy1t/b3RvLmZyLzIwMjUv/MTAvMTAvMDcvMTEv/aG9uZGEtbmVzLW1v/dG9ycmFkLWhvbmRh/LW5lcy0xMjVfMjUz/OTU0NDY4LmpwZw",
                            Vendedor_Id = 1
                        },
                        new
                        {
                            Id = 5,
                            Categoria_Id = 1,
                            Descripcion = "Vencida desierta",
                            Estado = "DESIERTA",
                            Fecha_Fin = new DateTime(2026, 9, 15, 21, 12, 57, 478, DateTimeKind.Local).AddTicks(9780),
                            Fecha_Inicio = new DateTime(2026, 9, 13, 21, 12, 57, 478, DateTimeKind.Local).AddTicks(9780),
                            Incremento_Minimo = 1000m,
                            Precio_Base = 30000m,
                            Titulo = "Monitor 4K",
                            Url_Imagen = "https://imgs.search.brave.com/GxxLh9QfgiHzyAdfGJdwmlCY3HDs81brY9Rr58XEfGI/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NjFlWFdSeGd4Skwu/anBn",
                            Vendedor_Id = 1
                        },
                        new
                        {
                            Id = 6,
                            Categoria_Id = 1,
                            Descripcion = "Vence el Sábado para probar pujas",
                            Estado = "ACTIVA",
                            Fecha_Fin = new DateTime(2026, 9, 21, 21, 12, 57, 478, DateTimeKind.Local).AddTicks(9780),
                            Fecha_Inicio = new DateTime(2026, 9, 17, 21, 12, 57, 478, DateTimeKind.Local).AddTicks(9780),
                            Incremento_Minimo = 2000m,
                            Precio_Base = 80000m,
                            Titulo = "Smart TV Samsung 55'",
                            Url_Imagen = "https://imgs.search.brave.com/jJ3FtIEDfioe0Qx2YFJLbqkKmZJ_xxLZQjm6zW1P3b0/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/OTFibFNpckVqT0wu/anBn",
                            Vendedor_Id = 1
                        },
                        new
                        {
                            Id = 7,
                            Categoria_Id = 1,
                            Descripcion = "Vence el Domingo para probar pujas",
                            Estado = "ACTIVA",
                            Fecha_Fin = new DateTime(2026, 9, 22, 21, 12, 57, 478, DateTimeKind.Local).AddTicks(9780),
                            Fecha_Inicio = new DateTime(2026, 9, 17, 21, 12, 57, 478, DateTimeKind.Local).AddTicks(9780),
                            Incremento_Minimo = 3000m,
                            Precio_Base = 120000m,
                            Titulo = "PlayStation 5",
                            Url_Imagen = "https://imgs.search.brave.com/TZ19Apjni8mGzUZkWey-zYtFy4VZ6lDLhLxrWhSQesQ/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/ZW5nYWRnZXQuY29t/L2ltZy9nYWxsZXJ5/L2hvdy1sb25nLWNh/bi15b3UtZXhwZWN0/LWEtcGxheXN0YXRp/b24tNS10by1sYXN0/L2ludHJvLTE3ODUx/NTQ5MDUuanBn",
                            Vendedor_Id = 1
                        });
                });

            modelBuilder.Entity("Domain.Transaccion_Ledger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Billetera_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Subasta_Id")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Billetera_Id");

                    b.HasIndex("Subasta_Id");

                    b.ToTable("Transacciones_Ledger");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Billetera_Id = 2,
                            Fecha = new DateTime(2026, 9, 12, 21, 12, 57, 478, DateTimeKind.Local).AddTicks(9780),
                            Monto = 150000m,
                            Tipo = "DEPOSITO"
                        },
                        new
                        {
                            Id = 2,
                            Billetera_Id = 3,
                            Fecha = new DateTime(2026, 9, 12, 21, 12, 57, 478, DateTimeKind.Local).AddTicks(9780),
                            Monto = 200000m,
                            Tipo = "DEPOSITO"
                        },
                        new
                        {
                            Id = 3,
                            Billetera_Id = 4,
                            Fecha = new DateTime(2026, 9, 12, 21, 12, 57, 478, DateTimeKind.Local).AddTicks(9780),
                            Monto = 500m,
                            Tipo = "DEPOSITO"
                        },
                        new
                        {
                            Id = 4,
                            Billetera_Id = 2,
                            Fecha = new DateTime(2026, 9, 17, 21, 2, 57, 478, DateTimeKind.Local).AddTicks(9780),
                            Monto = 45000m,
                            Subasta_Id = 1,
                            Tipo = "RETENCION"
                        },
                        new
                        {
                            Id = 5,
                            Billetera_Id = 3,
                            Fecha = new DateTime(2026, 9, 16, 21, 12, 57, 478, DateTimeKind.Local).AddTicks(9780),
                            Monto = 120000m,
                            Subasta_Id = 4,
                            Tipo = "DEBITO"
                        });
                });

            modelBuilder.Entity("Domain.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Fecha_Registro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password_Hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "vendedor@test.com",
                            Fecha_Registro = new DateTime(2026, 8, 18, 21, 12, 57, 478, DateTimeKind.Local).AddTicks(9780),
                            Nombre = "Vendedor",
                            Password_Hash = "$2y$10$TodzyNai9KReU03EQu46Y.OG28bJbBSupc2PT8BXgeTbINfVWEJuK"
                        },
                        new
                        {
                            Id = 2,
                            Email = "comprador1@test.com",
                            Fecha_Registro = new DateTime(2026, 8, 28, 21, 12, 57, 478, DateTimeKind.Local).AddTicks(9780),
                            Nombre = "Comprador Lider",
                            Password_Hash = "$2y$10$TodzyNai9KReU03EQu46Y.OG28bJbBSupc2PT8BXgeTbINfVWEJuK"
                        },
                        new
                        {
                            Id = 3,
                            Email = "comprador2@test.com",
                            Fecha_Registro = new DateTime(2026, 9, 2, 21, 12, 57, 478, DateTimeKind.Local).AddTicks(9780),
                            Nombre = "Comprador Habilitado",
                            Password_Hash = "$2y$10$TodzyNai9KReU03EQu46Y.OG28bJbBSupc2PT8BXgeTbINfVWEJuK"
                        },
                        new
                        {
                            Id = 4,
                            Email = "sinfondos@test.com",
                            Fecha_Registro = new DateTime(2026, 9, 7, 21, 12, 57, 478, DateTimeKind.Local).AddTicks(9780),
                            Nombre = "Usuario Sin Fondos",
                            Password_Hash = "$2y$10$TodzyNai9KReU03EQu46Y.OG28bJbBSupc2PT8BXgeTbINfVWEJuK"
                        });
                });

            modelBuilder.Entity("Domain.Auditoria_Log", b =>
                {
                    b.HasOne("Domain.Usuario", "Usuario")
                        .WithMany("Auditorias")
                        .HasForeignKey("Usuario_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Billetera", b =>
                {
                    b.HasOne("Domain.Usuario", "Usuario")
                        .WithOne("Billetera")
                        .HasForeignKey("Domain.Billetera", "Usuario_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Puja", b =>
                {
                    b.HasOne("Domain.Usuario", "Comprador")
                        .WithMany("Pujas")
                        .HasForeignKey("Comprador_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Subasta", "Subasta")
                        .WithMany("Pujas")
                        .HasForeignKey("Subasta_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comprador");

                    b.Navigation("Subasta");
                });

            modelBuilder.Entity("Domain.Subasta", b =>
                {
                    b.HasOne("Domain.Categoria", "Categoria")
                        .WithMany("Subastas")
                        .HasForeignKey("Categoria_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Usuario", "Vendedor")
                        .WithMany("Subastas")
                        .HasForeignKey("Vendedor_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("Domain.Transaccion_Ledger", b =>
                {
                    b.HasOne("Domain.Billetera", "Billetera")
                        .WithMany("Transacciones")
                        .HasForeignKey("Billetera_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Subasta", "Subasta")
                        .WithMany("Transacciones")
                        .HasForeignKey("Subasta_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Billetera");

                    b.Navigation("Subasta");
                });

            modelBuilder.Entity("Domain.Billetera", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("Domain.Categoria", b =>
                {
                    b.Navigation("Subastas");
                });

            modelBuilder.Entity("Domain.Subasta", b =>
                {
                    b.Navigation("Pujas");

                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("Domain.Usuario", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("Billetera")
                        .IsRequired();

                    b.Navigation("Pujas");

                    b.Navigation("Subastas");
                });
#pragma warning restore 612, 618
        }
    }
}
