// <auto-generated />
using System;
using Infraestructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(SubastaDbContext))]
    [Migration("20260830003246_InitDB")]
    partial class InitDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Auditoria_Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle_Json")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Entidad_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Usuario_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Usuario_Id");

                    b.ToTable("Auditorias_Log");
                });

            modelBuilder.Entity("Domain.Billetera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Saldo_Disponible")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Saldo_Retenido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Saldo_Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Usuario_Id")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Usuario_Id")
                        .IsUnique();

                    b.ToTable("Billeteras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Saldo_Disponible = 0m,
                            Saldo_Retenido = 0m,
                            Saldo_Total = 0m,
                            Usuario_Id = 1,
                            Version = 1
                        },
                        new
                        {
                            Id = 2,
                            Saldo_Disponible = 105000m,
                            Saldo_Retenido = 45000m,
                            Saldo_Total = 150000m,
                            Usuario_Id = 2,
                            Version = 1
                        },
                        new
                        {
                            Id = 3,
                            Saldo_Disponible = 200000m,
                            Saldo_Retenido = 0m,
                            Saldo_Total = 200000m,
                            Usuario_Id = 3,
                            Version = 1
                        },
                        new
                        {
                            Id = 4,
                            Saldo_Disponible = 500m,
                            Saldo_Retenido = 0m,
                            Saldo_Total = 500m,
                            Usuario_Id = 4,
                            Version = 1
                        });
                });

            modelBuilder.Entity("Domain.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Tecnología"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Coleccionables"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Indumentaria"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Vehículos"
                        });
                });

            modelBuilder.Entity("Domain.Puja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Comprador_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_Puja")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Subasta_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Comprador_Id");

                    b.HasIndex("Subasta_Id");

                    b.ToTable("Pujas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comprador_Id = 3,
                            Fecha_Puja = new DateTime(2026, 10, 1, 11, 30, 0, 0, DateTimeKind.Utc),
                            Monto = 25000m,
                            Subasta_Id = 1
                        },
                        new
                        {
                            Id = 2,
                            Comprador_Id = 2,
                            Fecha_Puja = new DateTime(2026, 10, 1, 11, 50, 0, 0, DateTimeKind.Utc),
                            Monto = 45000m,
                            Subasta_Id = 1
                        },
                        new
                        {
                            Id = 3,
                            Comprador_Id = 3,
                            Fecha_Puja = new DateTime(2026, 9, 29, 12, 0, 0, 0, DateTimeKind.Utc),
                            Monto = 120000m,
                            Subasta_Id = 4
                        });
                });

            modelBuilder.Entity("Domain.Subasta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Categoria_Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha_Fin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_Inicio")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Incremento_Minimo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Precio_Base")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url_Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Vendedor_Id")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Categoria_Id");

                    b.HasIndex("Vendedor_Id");

                    b.ToTable("Subastas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria_Id = 1,
                            Descripcion = "Activa Estandar",
                            Estado = "ACTIVA",
                            Fecha_Fin = new DateTime(2026, 10, 1, 12, 25, 0, 0, DateTimeKind.Utc),
                            Fecha_Inicio = new DateTime(2026, 10, 1, 11, 0, 0, 0, DateTimeKind.Utc),
                            Incremento_Minimo = 500m,
                            Precio_Base = 10000m,
                            Titulo = "MacBook Pro",
                            Url_Imagen = "macbook.jpg",
                            Vendedor_Id = 1,
                            Version = 1
                        },
                        new
                        {
                            Id = 2,
                            Categoria_Id = 2,
                            Descripcion = "Activa Crítica",
                            Estado = "ACTIVA",
                            Fecha_Fin = new DateTime(2026, 10, 1, 12, 1, 0, 0, DateTimeKind.Utc),
                            Fecha_Inicio = new DateTime(2026, 10, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Incremento_Minimo = 100m,
                            Precio_Base = 5000m,
                            Titulo = "Reloj Antiguo",
                            Url_Imagen = "reloj.jpg",
                            Vendedor_Id = 1,
                            Version = 1
                        },
                        new
                        {
                            Id = 3,
                            Categoria_Id = 3,
                            Descripcion = "Próxima",
                            Estado = "PROGRAMADA",
                            Fecha_Fin = new DateTime(2026, 10, 3, 12, 0, 0, 0, DateTimeKind.Utc),
                            Fecha_Inicio = new DateTime(2026, 10, 2, 12, 0, 0, 0, DateTimeKind.Utc),
                            Incremento_Minimo = 1000m,
                            Precio_Base = 20000m,
                            Titulo = "Campera Cuero",
                            Url_Imagen = "campera.jpg",
                            Vendedor_Id = 1,
                            Version = 1
                        },
                        new
                        {
                            Id = 4,
                            Categoria_Id = 4,
                            Descripcion = "Vencida con ganador",
                            Estado = "ACTIVA",
                            Fecha_Fin = new DateTime(2026, 9, 30, 12, 0, 0, 0, DateTimeKind.Utc),
                            Fecha_Inicio = new DateTime(2026, 9, 26, 12, 0, 0, 0, DateTimeKind.Utc),
                            Incremento_Minimo = 5000m,
                            Precio_Base = 100000m,
                            Titulo = "Moto Honda",
                            Url_Imagen = "moto.jpg",
                            Vendedor_Id = 1,
                            Version = 1
                        },
                        new
                        {
                            Id = 5,
                            Categoria_Id = 1,
                            Descripcion = "Vencida desierta",
                            Estado = "ACTIVA",
                            Fecha_Fin = new DateTime(2026, 9, 29, 12, 0, 0, 0, DateTimeKind.Utc),
                            Fecha_Inicio = new DateTime(2026, 9, 28, 12, 0, 0, 0, DateTimeKind.Utc),
                            Incremento_Minimo = 1000m,
                            Precio_Base = 30000m,
                            Titulo = "Monitor 4K",
                            Url_Imagen = "monitor.jpg",
                            Vendedor_Id = 1,
                            Version = 1
                        });
                });

            modelBuilder.Entity("Domain.Transaccion_Ledger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Billetera_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Subasta_Id")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Billetera_Id");

                    b.HasIndex("Subasta_Id");

                    b.ToTable("Transacciones_Ledger");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Billetera_Id = 2,
                            Fecha = new DateTime(2026, 9, 21, 12, 0, 0, 0, DateTimeKind.Utc),
                            Monto = 150000m,
                            Tipo = "DEPOSITO"
                        },
                        new
                        {
                            Id = 2,
                            Billetera_Id = 3,
                            Fecha = new DateTime(2026, 9, 21, 12, 0, 0, 0, DateTimeKind.Utc),
                            Monto = 200000m,
                            Tipo = "DEPOSITO"
                        },
                        new
                        {
                            Id = 3,
                            Billetera_Id = 4,
                            Fecha = new DateTime(2026, 9, 21, 12, 0, 0, 0, DateTimeKind.Utc),
                            Monto = 500m,
                            Tipo = "DEPOSITO"
                        },
                        new
                        {
                            Id = 4,
                            Billetera_Id = 2,
                            Fecha = new DateTime(2026, 10, 1, 11, 50, 0, 0, DateTimeKind.Utc),
                            Monto = 45000m,
                            Subasta_Id = 1,
                            Tipo = "RETENCION"
                        },
                        new
                        {
                            Id = 5,
                            Billetera_Id = 3,
                            Fecha = new DateTime(2026, 9, 29, 12, 0, 0, 0, DateTimeKind.Utc),
                            Monto = 120000m,
                            Subasta_Id = 4,
                            Tipo = "RETENCION"
                        });
                });

            modelBuilder.Entity("Domain.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha_Registro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password_Hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "vendedor@test.com",
                            Fecha_Registro = new DateTime(2026, 10, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Vendedor",
                            Password_Hash = "hash1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "comprador1@test.com",
                            Fecha_Registro = new DateTime(2026, 10, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Comprador Lider",
                            Password_Hash = "hash2"
                        },
                        new
                        {
                            Id = 3,
                            Email = "comprador2@test.com",
                            Fecha_Registro = new DateTime(2026, 10, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Comprador Habilitado",
                            Password_Hash = "hash3"
                        },
                        new
                        {
                            Id = 4,
                            Email = "sinfondos@test.com",
                            Fecha_Registro = new DateTime(2026, 10, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Usuario Sin Fondos",
                            Password_Hash = "hash4"
                        });
                });

            modelBuilder.Entity("Domain.Auditoria_Log", b =>
                {
                    b.HasOne("Domain.Usuario", "Usuario")
                        .WithMany("Auditorias")
                        .HasForeignKey("Usuario_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Billetera", b =>
                {
                    b.HasOne("Domain.Usuario", "Usuario")
                        .WithOne("Billetera")
                        .HasForeignKey("Domain.Billetera", "Usuario_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Puja", b =>
                {
                    b.HasOne("Domain.Usuario", "Comprador")
                        .WithMany("Pujas")
                        .HasForeignKey("Comprador_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Subasta", "Subasta")
                        .WithMany("Pujas")
                        .HasForeignKey("Subasta_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comprador");

                    b.Navigation("Subasta");
                });

            modelBuilder.Entity("Domain.Subasta", b =>
                {
                    b.HasOne("Domain.Categoria", "Categoria")
                        .WithMany("Subastas")
                        .HasForeignKey("Categoria_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Usuario", "Vendedor")
                        .WithMany("Subastas")
                        .HasForeignKey("Vendedor_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("Domain.Transaccion_Ledger", b =>
                {
                    b.HasOne("Domain.Billetera", "Billetera")
                        .WithMany("Transacciones")
                        .HasForeignKey("Billetera_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Subasta", "Subasta")
                        .WithMany("Transacciones")
                        .HasForeignKey("Subasta_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Billetera");

                    b.Navigation("Subasta");
                });

            modelBuilder.Entity("Domain.Billetera", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("Domain.Categoria", b =>
                {
                    b.Navigation("Subastas");
                });

            modelBuilder.Entity("Domain.Subasta", b =>
                {
                    b.Navigation("Pujas");

                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("Domain.Usuario", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("Billetera")
                        .IsRequired();

                    b.Navigation("Pujas");

                    b.Navigation("Subastas");
                });
#pragma warning restore 612, 618
        }
    }
}
